################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
INO_SRCS += \
..\I2CSensor_v1.0.ino \
..\ImageDraw_ESP8266_v1.0.ino \
..\OpenWeather_ESP8266v1.0.ino \
..\SmartTouch_ESP8266_v1.0.ino \
..\Smart_Controller.ino \
..\TemperatureHumidity_Si7006A20_v1.0.ino \
..\Time_ESP8266_v1.0.ino \
..\TouchCapacitive_CAP1114_v1.0.ino \
..\UserInterface_ESP8266_v1.0.ino \
..\WifiManage_v1.0.ino 

CPP_SRCS += \
..\.ino.cpp 

LINK_OBJ += \
.\.ino.cpp.o 

INO_DEPS += \
.\I2CSensor_v1.0.ino.d \
.\ImageDraw_ESP8266_v1.0.ino.d \
.\OpenWeather_ESP8266v1.0.ino.d \
.\SmartTouch_ESP8266_v1.0.ino.d \
.\Smart_Controller.ino.d \
.\TemperatureHumidity_Si7006A20_v1.0.ino.d \
.\Time_ESP8266_v1.0.ino.d \
.\TouchCapacitive_CAP1114_v1.0.ino.d \
.\UserInterface_ESP8266_v1.0.ino.d \
.\WifiManage_v1.0.ino.d 

CPP_DEPS += \
.\.ino.cpp.d 


# Each subdirectory must supply rules for building sources it contributes
.ino.cpp.o: ../.ino.cpp
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

I2CSensor_v1.0.o: ../I2CSensor_v1.0.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

ImageDraw_ESP8266_v1.0.o: ../ImageDraw_ESP8266_v1.0.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

OpenWeather_ESP8266v1.0.o: ../OpenWeather_ESP8266v1.0.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

SmartTouch_ESP8266_v1.0.o: ../SmartTouch_ESP8266_v1.0.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

Smart_Controller.o: ../Smart_Controller.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

TemperatureHumidity_Si7006A20_v1.0.o: ../TemperatureHumidity_Si7006A20_v1.0.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

Time_ESP8266_v1.0.o: ../Time_ESP8266_v1.0.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

TouchCapacitive_CAP1114_v1.0.o: ../TouchCapacitive_CAP1114_v1.0.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

UserInterface_ESP8266_v1.0.o: ../UserInterface_ESP8266_v1.0.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '

WifiManage_v1.0.o: ../WifiManage_v1.0.ino
	@echo 'Building file: $<'
	@echo 'Starting C++ compile'
	"C:\Program Files\eclipse\arduinoPlugin\tools\esp8266\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-IC:/Program Files/eclipse/arduinoPlugin/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-IC:/Users/Carson/Desktop/workspace/Smart_Controller/Release/core" -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC  -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266  -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SPI" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_ILI9341\1.0.2" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Time\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\TimeAlarms\1.5.0" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\Adafruit_GFX_Library\1.1.3" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\AVR_Standard_C_Time_Library\1.8.0-4\src" -I"C:\Program Files\eclipse\arduinoPlugin\libraries\ArduinoJson\5.6.7" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\esp8266\src" -I"C:\Program Files\eclipse\arduinoPlugin\packages\esp8266\hardware\esp8266\2.3.0\libraries\SoftwareSerial" -I"C:\Users\Carson\Desktop\workspace\Smart_Controller\Fonts" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -D__IN_ECLIPSE__=1 -x c++ "$<" -o "$@"  -Wall
	@echo 'Finished building: $<'
	@echo ' '


